### ISSUE TITLE
Improving README.md File

### ISSUE THREAD

**Issue by Aniketbhanderi** [ChetnaNSharma/Alumni-Connect#10]
Hi @yash982000 I would like to improve README.md file by adding few links and images for better understanding of this project.
I request you to assign this task to me.

**Comment by yash982000** [comment]
@Aniketbhanderi Sure, please go on. 
But, the thing is that you have to first show me what changes you want to do as in readme.md contains a lot of things, I couldn't assign to someone specific. Come up with your changes and I will merge them if find suitable.

**Comment by KajalSinghBAGHEL** [comment]
I am GSSOC 21 participant I am a beginner and would like to work on this issue and learn new things, please assign me.

**Comment by yash982000** [comment]
@Aniketbhanderi If you want some more changes, feel free to do it and I will merge if found suitable.
Also, if you are open to designing screens, let me know , I have some designs ready.

**Comment by yash982000** [comment]
@KajalSinghBAGHEL Open a new issue, I will let you know what to do in that.

**Comment by Aniketbhanderi** [comment]
@yash982000 I have already added pull request for this issue #10 please review that too.

**Comment by yash982000** [comment]
> @yash982000 I have already added pull request for this issue #10 please review that too.

Done!!
