### ISSUE TITLE
Alumni model (backend)

### ISSUE THREAD

**Issue by mitalirs** [ChetnaNSharma/Alumni-Connect#108]
**Is your feature request related to a problem? Please describe.**

currently, there is no alumni model 

**Describe the solution you'd like**

Creating an alumni model file inside the models folder

**Describe alternatives you've considered**

create an alumni model with the following fields:
1. name
2. email
3. password
4. college
5. tokens
6. contact
7. current job details

@yash982000, @ChetnaNSharma can you please assign this issue to me?

**Comment by ChitvanRamani22** [comment]
@mitalirs can i work on this ?

**Comment by yash982000** [comment]
@mitalirs Assigned :)

Extremely sorry for the late response. You can add whatever backend as well as stuff left. Will get back to in few hours with update from my side.

**Comment by ChitvanRamani22** [comment]
This too

**Comment by GovindCodes** [comment]
@yash982000  I would love to work on this if Assigned me the same.
Thanks

**Comment by ChitvanRamani22** [comment]
> @yash982000  I would love to work on this if Assigned me the same.
> Thanks

@GovindCodes this has already been done.
