### ISSUE TITLE
saving tokens (backend)

### ISSUE THREAD

**Issue by mitalirs** [ChetnaNSharma/Alumni-Connect#109]
**Is your feature request related to a problem? Please describe.**

currently, after signing up the token which gets provided to the student user does not get saved to the tokens array of the student entry in the collection

**Describe the solution you'd like**

adding some code to the sign-in route to save the token to 'tokens' array

@yash982000, @ChetnaNSharma can you please assign this issue to me

**Comment by ChitvanRamani22** [comment]
@mitalirs could you please provide me your discord username. I want to ask something.

**Comment by yash982000** [comment]
@mitalirs Assigned :)

Extremely sorry for the late response. You can add whatever backend as well as stuff left. Will get back to in few hours with update from my side.
