### ISSUE TITLE
Front-end (Homepage) needs to be made

### ISSUE THREAD

**Issue by SAHU-01** [ChetnaNSharma/Alumni-Connect#11]
As this project does not have any index.html page so ,I'd like to work on this from scratch , contributing to the front-end part including logos, navbar ,footer, etc .

I hope you can assign me with this task as a GSSOC '21 participant.

**Comment by yash982000** [comment]
@SAHU-01 That task is assigned to someone else as per the FCFS rule. You may have to wait until we get any result from that assignee or I would say you must start with posting some more ideas in the Open to Ideas thread.
I have some other designs for pages as well. Let me know if you can do some complex pages involving inside features of this project.

**Comment by SAHU-01** [comment]
Yes surely I'd love to take up any frontend related tasks.

Moreover have you decided on the logo because I had some in mind If you are willing I can share those.

**Comment by yash982000** [comment]
@SAHU-01 Yes, sure. You can come up with some designs in a new issue and make a PR. If found suitable, I will merge it after requesting some changes.

Also, if you are open to working on the frontend, I have some of these designs for you. If you can do it, here they are and I will assign it to you.

https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Profile%20Page%20.png

https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Profile%20Page%20Pop-Up%20Cards.png

**Comment by yash982000** [comment]
@SAHU-01 Are there any updates?

**Comment by SAHU-01** [comment]
Yup I'm almost done with my design , i'll share it tommorow , if you don't like that then I'll start working on the code with your design

**Comment by SAHU-01** [comment]
![image](https://user-images.githubusercontent.com/71656941/113036826-5c14b800-91b2-11eb-98aa-f5387960792d.png)
![image](https://user-images.githubusercontent.com/71656941/113036840-5fa83f00-91b2-11eb-9b21-e54fe764b76b.png)
![image](https://user-images.githubusercontent.com/71656941/113036850-62a32f80-91b2-11eb-8c0f-4a4f020d6f91.png)

I'll add the components the way you mentioned in the above designs and i was thinking of having a thin footer for this page
Let me know if this design suits the webpage.

those four boxes would be filled with the different boxes you mentioned in your design
lastly your designs are too blurly could you please share a better image or atleast let me know the details of those boxes and i'll fill them accordingly.

**Comment by yash982000** [comment]
> ![image](https://user-images.githubusercontent.com/71656941/113036826-5c14b800-91b2-11eb-98aa-f5387960792d.png)
> ![image](https://user-images.githubusercontent.com/71656941/113036840-5fa83f00-91b2-11eb-9b21-e54fe764b76b.png)
> ![image](https://user-images.githubusercontent.com/71656941/113036850-62a32f80-91b2-11eb-8c0f-4a4f020d6f91.png)
> 
> I'll add the components the way you mentioned in the above designs and i was thinking of having a thin footer for this page
> Let me know if this design suits the webpage.
> 
> those four boxes would be filled with the different boxes you mentioned in your design
> lastly your designs are too blurry could you please share a better image or at least let me know the details of those boxes and I'll fill them in accordingly.

Sure.

Here is the Figma link of designs:- https://www.figma.com/file/cGCtHWRhqz1mbJwiKJGUr6/Untitled?node-id=0%3A1

**Comment by yash982000** [comment]
> > ![image](https://user-images.githubusercontent.com/71656941/113036826-5c14b800-91b2-11eb-98aa-f5387960792d.png)
> > ![image](https://user-images.githubusercontent.com/71656941/113036840-5fa83f00-91b2-11eb-9b21-e54fe764b76b.png)
> > ![image](https://user-images.githubusercontent.com/71656941/113036850-62a32f80-91b2-11eb-8c0f-4a4f020d6f91.png)
> > I'll add the components the way you mentioned in the above designs and i was thinking of having a thin footer for this page
> > Let me know if this design suits the webpage.
> > those four boxes would be filled with the different boxes you mentioned in your design
> > lastly your designs are too blurry could you please share a better image or at least let me know the details of those boxes and I'll fill them in accordingly.
> 
> Sure.
> 
> Here is the Figma link of designs:- https://www.figma.com/file/cGCtHWRhqz1mbJwiKJGUr6/Untitled?node-id=0%3A1

I hope you are able to access it. If not, let me know.

**Comment by SAHU-01** [comment]
I'll send you the preview after writing the code, once you approve of that ,i'll make a pr with  the code

**Comment by yash982000** [comment]
> I'll send you the preview after writing the code, once you approve of that ,i'll make a pr with the code

👍

**Comment by SAHU-01** [comment]
and for the first mokeup I have written the code, you can see how the website looks by clicking on this link:https://drive.google.com/file/d/1T1pWN7DdBSH7cP2reefYRCyEmgM-SCeQ/view?usp=sharing

**Comment by SAHU-01** [comment]
/cc @yash982000  the contents are not very clear here

https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Profile%20Page%20.png

https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Profile%20Page%20Pop-Up%20Cards.png

could you kindly share these details so that I can Make changes to the website accordingly

**Comment by yash982000** [comment]
> and for the first mokeup I have written the code, you can see how the website looks by clicking on this link:https://drive.google.com/file/d/1T1pWN7DdBSH7cP2reefYRCyEmgM-SCeQ/view?usp=sharing

This is fine but seems different from what we are thinking. It would be good if you can discuss with Chetna regarding this.

**Comment by yash982000** [comment]
> and for the first mokeup I have written the code, you can see how the website looks by clicking on this link:https://drive.google.com/file/d/1T1pWN7DdBSH7cP2reefYRCyEmgM-SCeQ/view?usp=sharing

Above, I have given you the Figma link of designs in case you missed it. That should be visible clearly. Let me know if you are not able to access it.

**Comment by SAHU-01** [comment]
I'm not able to access the figma file and chetna has not commented on any other work progress yet as well, if possible could you ask her opinions, so that we can proceed with work!

**Comment by yash982000** [comment]
> I'm not able to access the figma file and chetna has not commented on any other work progress yet as well, if possible could you ask her opinions, so that we can proceed with work!

Ok.
Try this:- https://www.figma.com/file/cGCtHWRhqz1mbJwiKJGUr6/Untitled?node-id=0%3A1

**Comment by yash982000** [comment]
> > I'm not able to access the figma file and chetna has not commented on any other work progress yet as well, if possible could you ask her opinions, so that we can proceed with work!
> 
> Ok.
> Try this:- https://www.figma.com/file/cGCtHWRhqz1mbJwiKJGUr6/Untitled?node-id=0%3A1

If this doesn't work, drop your email.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by yash982000** [comment]
@srishtuj2000 I don't have any problem. If Ankita doesn't reply in a couple of days, please put a reminder and I will assign it to you.

@SAHU-01 Please once confirm if you are not working so she can do it.

**Comment by SAHU-01** [comment]
Chetna doesn't intend to have this page so we dropped this page. Please ask her if she wants it now ,you can assign it again.
