### ISSUE TITLE
Adding Alert Box

### ISSUE THREAD

**Issue by vanshika2906** [ChetnaNSharma/Alumni-Connect#119]
**Describe the solution you'd like**
I would like to add a alert box just below the navbar saying something like. "Good Landing! Create a profile to get started". Will provide functionality that it will appear for only 5 seconds and then will disappear.
Please assign this to me. Thankyou!

**Comment by vanshika2906** [comment]
Somewhat like this below the navbar. Please assign this to me. Thankyou! 
![image](https://user-images.githubusercontent.com/65587816/119930565-50b8ef80-bf9d-11eb-994e-7b8f840847f0.png)

**Comment by yash982000** [comment]
@vanshika2906  Assigned :)

Extremely sorry for the late response. You can add whatever backend as well as stuff left. Will get back to in few hours with update from my side.
