### ISSUE TITLE
backend: Allow admin to perform various tasks

### ISSUE THREAD

**Issue by himanshujaidka** [ChetnaNSharma/Alumni-Connect#142]
I want to add accessibility to admin to perform various tasks, like deleteUser, updateUser and so on.

**Comment by ChitvanRamani22** [comment]
@himanshujaidka already implemented.

**Comment by himanshujaidka** [comment]
> @himanshujaidka already implemented.

Are you sure that all the actions are allowed?

**Comment by ChitvanRamani22** [comment]
Yes
