### ISSUE TITLE
Github ot Feature

### ISSUE THREAD

**Issue by Sukriti-sood** [ChetnaNSharma/Alumni-Connect#146]
Github Bot Will COmment on Every PR Open and PR merged

**Comment by yash982000** [comment]
@Sukriti-sood Can you please recheck?
There is already a bot for this feature I guess

If there is something different, please let me know and then I can assign and merge.

**Comment by Sukriti-sood** [comment]
@yash982000 At the time when I created issue , workflow did not exists but someone created pr after that and recently you merged , I was not aware that we can open pr without issue.

**Comment by yash982000** [comment]
> @yash982000 At the time when I created issue , workflow did not exists but someone created pr after that and recently you merged , I was not aware that we can open pr without issue.

Oh  okay. Do open some small issue or feature you want or some good changes in the documentation and readme and I will be happy to assign and merge and give suitable credits :)

**Comment by Sukriti-sood** [comment]
@yash982000 Thanks for the opportunity , I will surely Open a Issue.

**Comment by Sukriti-sood** [comment]
@yash982000  I have Opened a Issue #157
