### ISSUE TITLE
LOGO for Alumni-Connect

### ISSUE THREAD

**Issue by SAHU-01** [ChetnaNSharma/Alumni-Connect#15]
Well this website doesn't have any logo in particular so ,I got certain ideas and I'd like to share that here,
do let me know the designs you like then I can accordingly make customizations for your website
/cc @ChetnaNSharma @yash982000 

Here are few  designs:

![image](https://user-images.githubusercontent.com/71656941/112712111-4de54400-8ef3-11eb-96d5-6263a87ee3a9.png)

![image](https://user-images.githubusercontent.com/71656941/112712118-53db2500-8ef3-11eb-8cd5-f6a0915447f0.png)

![image](https://user-images.githubusercontent.com/71656941/112712147-8d139500-8ef3-11eb-9ab1-64c12beeb840.png)

![image](https://user-images.githubusercontent.com/71656941/112712123-5c336000-8ef3-11eb-8e66-6145d1656454.png)

**Comment by ChetnaNSharma** [comment]
Hi Ankita 
We are thankful for your attempt. 
The logo doesn't need to have variety of colors. Can you design something consisting of different shades of grey?

**Comment by SAHU-01** [comment]
sure chetna I'll do that and share the design by midnight

**Comment by SAHU-01** [comment]
Well here are few designs let me know if you like anything in particular or  if you want something other than the letters "ac " as the logo

here are  the rough sketches:

![image](https://user-images.githubusercontent.com/71656941/112761684-03121c00-901a-11eb-8f7d-8b6fc6acb321.png)

![image](https://user-images.githubusercontent.com/71656941/112761690-07d6d000-901a-11eb-857b-aeab24709f5d.png)

![image](https://user-images.githubusercontent.com/71656941/112761697-16bd8280-901a-11eb-8fd4-96c6a8bb7e9f.png)

**Comment by SAHU-01** [comment]
/cc @ChetnaNSharma  let me know if you like any of these ac designs then I can work on the colors but lets fix a design first.

![image](https://user-images.githubusercontent.com/71656941/112765223-ce0dc580-9029-11eb-8301-738227f81249.png)
![image](https://user-images.githubusercontent.com/71656941/112765228-d239e300-9029-11eb-9d35-4603794b4c83.png)
![image](https://user-images.githubusercontent.com/71656941/112765233-d960f100-9029-11eb-9609-4fd112c39559.png)
![image](https://user-images.githubusercontent.com/71656941/112765236-dc5be180-9029-11eb-827a-14f8e82577ea.png)
<img width="82" alt="a1" src="https://user-images.githubusercontent.com/71656941/112765244-e41b8600-9029-11eb-9ca4-e09b1d1d68d3.png">
<img width="49" alt="a2" src="https://user-images.githubusercontent.com/71656941/112765250-eb429400-9029-11eb-8576-ab2ddcbe9b08.png">

![image](https://user-images.githubusercontent.com/71656941/112765230-d5cd6a00-9029-11eb-8698-fde2a1aea649.png)

**Comment by M2kishore** [comment]
> ![image](https://user-images.githubusercontent.com/71656941/112765228-d239e300-9029-11eb-9d35-4603794b4c83.png)
This one looks cool :)     (suggestion)

**Comment by prathamesh3707** [comment]
Can I work on it

**Comment by yash982000** [comment]
@prathamesh3707 Sure.
Let me know if you want to so that I can assign you.

**Comment by prathamesh3707** [comment]
Yes I would do it.

**Comment by yash982000** [comment]
> Yes I would do it.

@prathamesh3707 Assigned.
