### ISSUE TITLE
backend: need for the new models for the alumni

### ISSUE THREAD

**Issue by himanshujaidka** [ChetnaNSharma/Alumni-Connect#151]
I have seen that in this there is only user and admin but the main focus of this web app is to connect with the alumni , so I think there would be another backend system for the alumni? what do you think @ChetnaNSharma

**Comment by yash982000** [comment]
> I have seen that in this there is only user and admin but the main focus of this web app is to connect with the alumni , so I think there would be another backend system for the alumni? what do you think @ChetnaNSharma

User ultimately becomes the alumni as per their year of graduation.

**Comment by himanshujaidka** [comment]
okay
