### ISSUE TITLE
Feedback page/ Contact us page

### ISSUE THREAD

**Issue by RubenFalcao14** [ChetnaNSharma/Alumni-Connect#18]
I would like to build a page that lets users gives the moderator feedback about the website i.e the positive things that they like about the site , the issues that they are facing as well as some features that they would like to add to the site .

**Comment by RubenFalcao14** [comment]
I'm a GSSOC'21 participant and I would love to work on it.
Thank You.

**Comment by yash982000** [comment]
@RubenFalcao14 Hey, if you want to make something like that, I can give you something related to it.

![image](https://user-images.githubusercontent.com/44220455/112761506-428c3880-9019-11eb-9414-d0e1f386f858.png)

Here is what you have to do, below the search bar in the above image, you have to put review cards of customers/users who have given the review.
Something like this:-https://youtu.be/O-QUBZuZlXM
Let me know if you can do it in a couple of days.

**Comment by RubenFalcao14** [comment]
I'll try my best , Thank You Sir.

**Comment by yash982000** [comment]
Most Welcome. All the Best :)

**Comment by yash982000** [comment]
@RubenFalcao14 Any updates about the review cards thing? We want it as soon as possible as there are a number of other contributors asking for the same task too. Let me know if you can do it or not

**Comment by RubenFalcao14** [comment]
It's almost done , I just need to sort out some minor issues I'll send you some pics , in about 1 day's time . Sorry for the delay .

**Comment by RubenFalcao14** [comment]
![mockup.JPG](https://user-images.githubusercontent.com/79042516/113076232-36a4a000-91ec-11eb-9f3e-46ea4a34b2a6.JPG)
Sir is it okay ?@yash982000

**Comment by yash982000** [comment]
> ![mockup.JPG](https://user-images.githubusercontent.com/79042516/113076232-36a4a000-91ec-11eb-9f3e-46ea4a34b2a6.JPG)
> Sir is it okay ?@yash982000

Works but there should be a pop-up kinda thing when the mouse pointer hover over it.

**Comment by RubenFalcao14** [comment]
I'll try to add it by today and send you a pic.

**Comment by RubenFalcao14** [comment]
![Screenshot (584).png](https://user-images.githubusercontent.com/79042516/113231105-1b06cb80-92b8-11eb-9e74-c40d0428f898.png)
@yash982000 Sir , I have added the hover effect to the review cards let me know if it's okay .

**Comment by yash982000** [comment]
> ![Screenshot (584).png](https://user-images.githubusercontent.com/79042516/113231105-1b06cb80-92b8-11eb-9e74-c40d0428f898.png)
> @yash982000 Sir , I have added the hover effect to the review cards let me know if it's okay .

@RubenFalcao14  It looks good. Can you add the code now?
Also, I hope you have made the CSS file too and it's responsive.

**Comment by RubenFalcao14** [comment]
@yash982000 Sir, have made 2 files 1 .html file and 1 .css file. Could you tell me where I should add them in the repo .

**Comment by yash982000** [comment]
> @yash982000 Sir, have made 2 files 1 .html file and 1 .css file. Could you tell me where I should add them in the repo .

Make a pull request by adding these files in a new folder named templates or similar.
