### ISSUE TITLE
creating a page which contains about alumni of college

### ISSUE THREAD

**Issue by arpit456jain** [ChetnaNSharma/Alumni-Connect#24]

**Comment by shefali12-ab** [comment]
@yash982000 issue is already created by @arpit456jain , now what should i do.

**Comment by shefali12-ab** [comment]
after adding those screens please , guide us like what we have to add further and what changes you need.

**Comment by ChetnaNSharma** [comment]
Hi Shefali
Can you tell me what screens are you talking about?

**Comment by shefali12-ab** [comment]
> Hi Shefali
> Can you tell me what screens are you talking about?

sorry, i mean designs that you are adding.

**Comment by yash982000** [comment]
> @yash982000 issue is already created by @arpit456jain , now what should i do.

Please open different than him, we have other tasks too.

**Comment by shefali12-ab** [comment]
> > @yash982000 issue is already created by @arpit456jain , now what should i do.
> 
> Please open different than him, we have other tasks too.

okay, tell me what should i name that issue.

**Comment by yash982000** [comment]
> > > @yash982000 issue is already created by @arpit456jain , now what should i do.
> > 
> > 
> > Please open different than him, we have other tasks too.
> 
> okay, tell me what should i name that issue.

Anything that you are willing to contribute :)

**Comment by arpit456jain** [comment]
@yash982000 can you please guide me what to do.

**Comment by yash982000** [comment]
> @yash982000 can you please guide me what to do.

Yes, sure.

You may start working on these designs.

https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Resources%20Page%20-%201.png

https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Resources%20Page%20-%202.png

**Comment by yash982000** [comment]
> > @yash982000 can you please guide me what to do.
> 
> Yes, sure.
> 
> You may start working on these designs.
> 
> https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Resources%20Page%20-%201.png
> 
> https://github.com/ChetnaNSharma/Alumni-Connect/blob/main/Alumni%20Connect%20Design%20Screens/Alumni%20Connect%20Resources%20Page%20-%202.png

@arpit456jain
