### ISSUE TITLE
Adding a 404 page

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [ChetnaNSharma/Alumni-Connect#31]
I would like to add a 404 page to the website.

**Comment by yash982000** [comment]
> I would like to add a 404 page to the website.

I guess this issue is being worked on by you itself on a different thread if I am not wrong.
If so, please confirm so that I can close this one.

**Comment by ShambhaviSharma0110** [comment]
I'm done with the 404 page, I've made the pr as well... you can close it

**Comment by yash982000** [comment]
> I'm done with the 404 page, I've made the pr as well... you can close it

Ok, done!!
