### ISSUE TITLE
Regarding opening issues

### ISSUE THREAD

**Issue by Jassi10000-zz** [ChetnaNSharma/Alumni-Connect#32]
@yash982000  Sir ,are there no issues available from the maintainers' side 
Do we have to open issues of our own , to work ?

**Comment by yash982000** [comment]
> @yash982000 Sir ,are there no issues available from the maintainers' side
> Do we have to open issues of our own , to work ?

Yes @Jassi10000 Once you are interested, you can open an issue and I will give you some tasks.

**Comment by yash982000** [comment]
@Jassi10000 You can open a new issue and I will assign you task on a new thread.
