### ISSUE TITLE
Improvement in the testimonials section

### ISSUE THREAD

**Issue by Khushi-agarwal** [ChetnaNSharma/Alumni-Connect#40]
The testimonial page can be improved by adding animation and also adding a hover effect on them.
please @mksharma1 @Aniketbhanderi @yash982000 @M2kishore @pragati-kumar  assign this issue to me.

**Comment by yash982000** [comment]
> The testimonial page can be improved by adding animation and also adding a hover effect on them.
> please @mksharma1 @Aniketbhanderi @yash982000 @M2kishore @pragati-kumar assign this issue to me.

@Khushi-agarwal The hover part is done. The animation you may feel free to do.
Related to this, I have some similar tasks too if you can do. You have to make a box or table kind of thing where one can see the requests.
These requests will be asked to the Alumni from the users/junior college students about asking them for a profile/resume/LinkedIn review. It should look like a connection request sent on Linkedin or a friend request on facebook.
The only difference is it will directly contain the link of the Linkedin or resume of that user.

Something like below:-
![image](https://user-images.githubusercontent.com/44220455/113502668-5c62d980-954b-11eb-859f-10df7d049b44.png)
Here, you can see the requests section, where a table of pending requests along with their profile or resume link should be seen.

I have assigned you. Let m know if you can do it or not.

**Comment by Khushi-agarwal** [comment]
The link of the linkedin or resume of the user will also be in the form of table in the request section?

**Comment by Khushi-agarwal** [comment]
Yes @yash982000 I can do it.

**Comment by yash982000** [comment]
> Yes @yash982000 I can do it.

Great!! 
Please do it and make a PR soon as you complete.

**Comment by Khushi-agarwal** [comment]
I have created a pr #42 . please @yash982000 review it.

**Comment by yash982000** [comment]
> I have created a pr #42 . please @yash982000 review it.

@Khushi-agarwal Yes, I am checking there and closing this issue.

**Comment by Khushi-agarwal** [comment]
@yash982000 Can you please add labels to this.
