### ISSUE TITLE
Updating the marking scheme of GSSOC in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by akshatvirmani** [ChetnaNSharma/Alumni-Connect#43]
There is a change in the marking scheme of GSSOC for different level issues.

**Comment by akshatvirmani** [comment]
Kindly assign me this issue so I can work on it.

**Comment by yash982000** [comment]
> Kindly assign me this issue so I can work on it.

Done!!

**Comment by yash982000** [comment]
> Kindly assign me this issue so I can work on it.

Any updates? @akshatvirmani 

Let me know so that we can close this issue or assign it appropriately.
