### ISSUE TITLE
Making ABOUT US  and CONTACT US page

### ISSUE THREAD

**Issue by kumarishalini6** [ChetnaNSharma/Alumni-Connect#47]
There is noting in about us and contact us page i want to work on this issue under GSSoC'21

**Comment by hritikgupta92** [comment]
Can I also work with you on this issue?

**Comment by samgarg7009** [comment]
Can I also work with you on this issue ?

**Comment by yash982000** [comment]
@kumarishalini6 I am assigning you this as you came first.
But @hritikgupta92 and @samgarg7009 You both can contribute too. You both can start for other pages as well.
Make sure it aligns with the project designs and opens a new issue or PR independently.  Rech out to me on Whatsapp or discord DM in case I am not replying here and for faster assistance.

**Comment by kumarishalini6** [comment]
Thanks for assigning me .
Can you please add labels in this issue

**Comment by hritikgupta92** [comment]
> @kumarishalini6 I am assigning you this as you came first.
> But @hritikgupta92 and @samgarg7009 You both can contribute too. You both can start for other pages as well.
> Make sure it aligns with the project designs and opens a new issue or PR independently. Rech out to me on Whatsapp or discord DM in case I am not replying here and for faster assistance.

Ok

**Comment by samgarg7009** [comment]
Ok

**Comment by kumarishalini6** [comment]
Close this also
