### ISSUE TITLE
Creating a student model 

### ISSUE THREAD

**Issue by mitalirs** [ChetnaNSharma/Alumni-Connect#49]
Currently, there is no backend code to handle users. I will create a separate directory to handle the backend part, inside the 'models' folder I will create a 'student' model based on a studentSchema. The student will have the following attributes:
name, year, email Id, password, branch. I will be doing the setup using node and express
@ChetnaNSharma, @yash982000 can you please assign this issue to me?

**Comment by yash982000** [comment]
> Currently, there is no backend code to handle users. I will create a separate directory to handle the backend part, inside the 'models' folder I will create a 'student' model based on a studentSchema. The student will have the following attributes:
> name, year, email Id, password, branch. I will be doing the setup using node and express
> @ChetnaNSharma, @yash982000 can you please assign this issue to me?

@mitalirs Sure. Just make sure about our project requirements and goal.
Also, stick to Node if possible. :)

**Comment by mitalirs** [comment]
@yash982000 sure, thank you for assigning this issue to me
Also, will it be okay if I add the student model once the initial folder setup is done, I guess @Kriti-bit has been assigned to do that, right?

**Comment by yash982000** [comment]
> @yash982000 sure, thank you for assigning this issue to me
> Also, will it be okay if I add the student model once the initial folder setup is done, I guess @Kriti-bit has been assigned to do that, right?

Yes, you can have mutual discussions and update me accordingly
