### ISSUE TITLE
adding contributing.md

### ISSUE THREAD

**Issue by vanieka-sharma** [ChetnaNSharma/Alumni-Connect#5]
Hi ! I would like to create a file named contributing.md which will
Add the following -

1.Difference between GIT and GITHUB
2.How to clone, fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updation are made in the upstream
@ChetnaNSharma 
I would like to work on this as a part of GSSOC'21 can you please assign me

**Comment by yash982000** [comment]
> Hi ! I would like to create a file named contributing.md which will
> Add the following -
> 
> 1.Difference between GIT and GITHUB
> 2.How to clone, fork repository
> 3.How to create a branch and then use git push to push to repo
> 4.Create a PR
> 5.Squash commits in a single issue into one
> 6, Updating the forked and local repo as the updation are made in the upstream
> @ChetnaNSharma
> I would like to work on this as a part of GSSOC'21 can you please assign me

@vanieka-sharma Thank you for your interest. This is a good part of any repository. I am assigning this to you. Please have detailed information and steps required. We will make changes and requirements as needed.

**Comment by vanieka-sharma** [comment]
@yash982000 I have made pull request, please review that and please tell if any changes required. Thankyou

**Comment by yash982000** [comment]
@vanieka-sharma I am merging this at the moment. Still, it requires some changes for which you can do the pull request again.

**Comment by vanieka-sharma** [comment]
@yash982000 Hello Sir can you please tell the Level of this contribution as I have to fill the feedback form

**Comment by pragati-kumar** [comment]
> @vanieka-sharma I am merging this at the moment. Still, it requires some changes for which you can do the pull request again.

@yash982000 I could work on the further streamlining of the documentation, sir if that's acceptable? Steps for committing changes could be added.

**Comment by yash982000** [comment]
> @yash982000 Hello Sir can you please tell the Level of this contribution as I have to fill the feedback form

Heyy, @vanieka-sharma Could you please provide me with the docs which have this information of contribution levels from GSSoC so that I can give it to you. Somehow I am unable to find it.

**Comment by yash982000** [comment]
> > @vanieka-sharma I am merging this at the moment. Still, it requires some changes for which you can do the pull request again.
> 
> @yash982000 I could work on the further streamlining of the documentation, sir if that's acceptable? Steps for committing changes could be added.

Yes @pragati-kumar You can surely work. Do it more detailed and open a pull request. I will merge it after relevant changes.

**Comment by pragati-kumar** [comment]
@yash982000 Sent the PR please check. Let me know if any updates are required.

**Comment by yash982000** [comment]
> @yash982000 Sent the PR please check. Let me know if any updates are required.

I think I merged it right now. It was regarding same right?

**Comment by M2kishore** [comment]
Just found a minor spelling mistake in contributing.md
fee -> feel(marked with blue ink)
![image](https://user-images.githubusercontent.com/60045529/113386030-f5a4bb00-93a6-11eb-8415-c812351b288b.png)

**Comment by yash982000** [comment]
> Just found a minor spelling mistake in contributing.md
> fee -> feel(marked with blue ink)
> ![image](https://user-images.githubusercontent.com/60045529/113386030-f5a4bb00-93a6-11eb-8415-c812351b288b.png)

Make a PR and I will merge it. @M2kishore

**Comment by yash982000** [comment]
> @yash982000 Sent the PR please check. Let me know if any updates are required.

@pragati-kumar Can you let me know if this issue is done? As in I have many issues and PR to handle and it becomes somewhat complex and confusing for me. So, I want to close this issue if it is done.

**Comment by pragati-kumar** [comment]
> > @yash982000 Sent the PR please check. Let me know if any updates are required.
> 
> @pragati-kumar Can you let me know if this issue is done? As in I have many issues and PR to handle and it becomes somewhat complex and confusing for me. So, I want to close this issue if it is done.

Yes, sir. The spelling mistake has been corrected now too so you could close the issue if you please.

**Comment by yash982000** [comment]
> > > @yash982000 Sent the PR please check. Let me know if any updates are required.
> > 
> > 
> > @pragati-kumar Can you let me know if this issue is done? As in I have many issues and PR to handle and it becomes somewhat complex and confusing for me. So, I want to close this issue if it is done.
> 
> Yes, sir. The spelling mistake has been corrected now too so you could close the issue if you please.

Great, thanks @pragati-kumar for letting me know. :)
