### ISSUE TITLE
[Backend] Initial Server Setup

### ISSUE THREAD

**Issue by Kriti-bit** [ChetnaNSharma/Alumni-Connect#50]
I would like to start working on the backend.
-Add dependencies
-Connect Database
-Add required models
-Set up routes as needed

**Comment by Kriti-bit** [comment]
I am a GSSoC'21 Participant. Please assign this issue to me.

**Comment by yash982000** [comment]
> I would like to start working on the backend.
> -Add dependencies
> -Connect Database
> -Add required models
> -Set up routes as needed

@Kriti-bit Done, All the Best :)

**Comment by yash982000** [comment]
> I am a GSSoC'21 Participant. Please assign this issue to me.

Any updates? @Kriti-bit 

Let me know on WhatsApp or discord so that we can close this issue or assign it appropriately.
DM on discord if you need my contact info for discussing your work or any other doubts.
