### ISSUE TITLE
Opportunity Page

### ISSUE THREAD

**Issue by avinashjha1320** [ChetnaNSharma/Alumni-Connect#55]

**Comment by yash982000** [comment]
> _No description provided._

@avinashjha1320 Any reference?

**Comment by avinashjha1320** [comment]
![JobBoard — Website Template by Colorlib - Brave 4_13_2021 10_42_59 AM](https://user-images.githubusercontent.com/71824792/114500261-4b9a1e00-9c45-11eb-912d-6ba9e77121e9.png)
![image](https://user-images.githubusercontent.com/71824792/114500346-73898180-9c45-11eb-8563-d2fef739c298.png)

@yash982000 I have provided these two references to the project admin...she will choose the design and then I can proceed with the development part.

**Comment by yash982000** [comment]
> ![JobBoard — Website Template by Colorlib - Brave 4_13_2021 10_42_59 AM](https://user-images.githubusercontent.com/71824792/114500261-4b9a1e00-9c45-11eb-912d-6ba9e77121e9.png)
> ![image](https://user-images.githubusercontent.com/71824792/114500346-73898180-9c45-11eb-8563-d2fef739c298.png)
> 
> @yash982000 I have provided these two references to the project admin...she will choose the design and then I can proceed with the development part.

Okay, @avinashjha1320

**Comment by avinashjha1320** [comment]
@yash982000 can you please tell me which design should I continue and assign me this issue.

**Comment by yash982000** [comment]
> @yash982000 can you please tell me which design should I continue and assign me this issue.

@avinashjha1320 Take the 2nd one
