### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by avinashjha1320** [ChetnaNSharma/Alumni-Connect#57]
@yash982000 @ChetnaNSharma Here are some of the templates for the profile page...can you help me out by selecting any of them or by giving and another sample.
### Sample 1
![image](https://user-images.githubusercontent.com/71824792/114519341-f28ab400-9c5d-11eb-8718-c91c9499db5c.png)
### Sample 2
![image](https://user-images.githubusercontent.com/71824792/114520204-d1769300-9c5e-11eb-997e-5ea0df67bb96.png)
### Sample 3
![image](https://user-images.githubusercontent.com/71824792/114520524-2a462b80-9c5f-11eb-8812-db54526e5f83.png)

**Comment by yash982000** [comment]
> @yash982000 @ChetnaNSharma Here are some of the templates for the profile page...can you help me out by selecting any of them or by giving and another sample.
> 
> ### Sample 1
> ![image](https://user-images.githubusercontent.com/71824792/114519341-f28ab400-9c5d-11eb-8718-c91c9499db5c.png)
> 
> ### Sample 2
> ![image](https://user-images.githubusercontent.com/71824792/114520204-d1769300-9c5e-11eb-997e-5ea0df67bb96.png)
> 
> ### Sample 3
> ![image](https://user-images.githubusercontent.com/71824792/114520524-2a462b80-9c5f-11eb-8812-db54526e5f83.png)

@avinashjha1320 The first one looks good. It is also similar to what has been added in our designs folder.

**Comment by avinashjha1320** [comment]
@yash982000 So can you please assign this to me? so that I can procced with the development of the page.

**Comment by yash982000** [comment]
> @yash982000 So can you please assign this to me? so that I can procced with the development of the page.

Assigned
