### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by ChitvanRamani22** [ChetnaNSharma/Alumni-Connect#65]
@yash982000 i would like to design footer for the website., that would be available on every page.
Please assign it to me.

**Comment by yash982000** [comment]
> @yash982000 i would like to design footer for the website., that would be available on every page.
> Please assign it to me.

Done!!

**Comment by SnehaVeerakumar** [comment]
I would like to work on this issue. If the present assignee gets unassigned, please assign me to complete this issue in 2 days. 
@yash982000

**Comment by ChitvanRamani22** [comment]
> I would like to work on this issue. If the present assignee gets unassigned, please assign me to complete this issue in 2 days. 
> @yash982000 

@SnehaVeerakumar the pr of this issue is already merged.

**Comment by SnehaVeerakumar** [comment]
> > I would like to work on this issue. If the present assignee gets unassigned, please assign me to complete this issue in 2 days.
> > @yash982000
> 
> @SnehaVeerakumar the pr of this issue is already merged.

How do I find issues with unmerged PRs ?

**Comment by yash982000** [comment]
> > > I would like to work on this issue. If the present assignee gets unassigned, please assign me to complete this issue in 2 days.
> > > @yash982000
> > 
> > 
> > @SnehaVeerakumar the pr of this issue is already merged.
> 
> How do I find issues with unmerged PRs ?


@SnehaVeerakumar  Generally open issues have PR left to be merged.

@ChitvanRamani22 Close the issues if the PR is merged to avoid confusion.
