### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by ChitvanRamani22** [ChetnaNSharma/Alumni-Connect#66]
Would like to make 404 page more attractive that will appear if the user enters the url that is not available and also this page will have a home link that will redirect the user to home page.
@yash982000 please assign it to me.

**Comment by yash982000** [comment]
> Would like to make 404 page more attractive that will appear if the user enters the url that is not available and also this page will have a home link that will redirect the user to home page.
> @yash982000 please assign it to me.

Done!!

**Comment by ChitvanRamani22** [comment]
@yash982000 please assign and also add labels to it.

**Comment by ChitvanRamani22** [comment]
@yash982000 i will be creating and styling the page and then creating route and then linking i think it is a level 2 issue.
