### ISSUE TITLE
Recommendation Page

### ISSUE THREAD

**Issue by avinashjha1320** [ChetnaNSharma/Alumni-Connect#67]
@yash982000 @ChetnaNSharma I want to build the recommendation page where different user accounts are referred for connection. Similar to the recommendation page of LinkedIn.

**Comment by yash982000** [comment]
> @yash982000 @ChetnaNSharma I want to build the recommendation page where different user accounts are referred for connection. Similar to the recommendation page of LinkedIn.

Assigned
