### ISSUE TITLE
Hover Effect to Buttons

### ISSUE THREAD

**Issue by vanshika2906** [ChetnaNSharma/Alumni-Connect#70]
I would like to design the navbar by changing font and wants to provide a hovering effect to the components like Home, About-Us, Contact-Us, Services.
Please assign this issue to me.

**Comment by yash982000** [comment]
> I would like to design the navbar by changing font and wants to provide a hovering effect to the components like Home, About-Us, Contact-Us, Services.
> Please assign this issue to me.

Done @vanshika2906
