### ISSUE TITLE
Pre Loader

### ISSUE THREAD

**Issue by ChitvanRamani22** [ChetnaNSharma/Alumni-Connect#82]
I want to add preloader to the website.
I will use suspense,lazy to fetch and show preload until all the data is being loaded.
@yash982000 please assign this to me.

**Comment by yash982000** [comment]
> I want to add preloader to the website.
> I will use suspense,lazy to fetch and show preload until all the data is being loaded.
> @yash982000 please assign this to me.

@ChitvanRamani22 Please describe a bit more. I am not exactly able to understand what it is and how will it be helpful for us in this project.

**Comment by ChitvanRamani22** [comment]
@yash982000 https://user-images.githubusercontent.com/76901313/114297933-46b45d80-9ad1-11eb-9633-be4359257b9d.mp4
We could add an interactive splash screen like this just before opening of every page ,it will look good.

**Comment by yash982000** [comment]
> @yash982000 https://user-images.githubusercontent.com/76901313/114297933-46b45d80-9ad1-11eb-9633-be4359257b9d.mp4
> We could add an interactive splash screen like this just before the opening of every page, it will look good.

According to my, this is not much suitable for a portal of well-established Alumni. I think it lacks professionalism.
If you want, you can try which looks more professional.

**Comment by yash982000** [comment]
> > @yash982000 https://user-images.githubusercontent.com/76901313/114297933-46b45d80-9ad1-11eb-9633-be4359257b9d.mp4
> > We could add an interactive splash screen like this just before the opening of every page, it will look good.
> 
> According to my, this is not much suitable for a portal of well-established Alumni. I think it lacks professionalism.
> If you want, you can try which looks more professional.

@ChitvanRamani22
