### ISSUE TITLE
Create ChatBot feature

### ISSUE THREAD

**Issue by vanshika2906** [ChetnaNSharma/Alumni-Connect#88]
**Is your feature request related to a problem? Please describe.**
Adding  a chatbot feature in the web app.
A button  showing click to chat at the bottom on the home page.

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me

**Comment by yash982000** [comment]
@vanshika2906 You can work on this. Assigned :)

@Furquan712 Please find some other open issue to work on it or come with any new feature/suggestion/idea.
We have the First Come First Serve rule so cannot help with this issue. However, you both might collaborate if want.
