### ISSUE TITLE
LOGIN PAGE

### ISSUE THREAD

**Issue by ANSHIKA1806** [ChetnaNSharma/Alumni-Connect#9]
@yash982000 @mksharma1 @vanieka-sharma  I want to create login page as given in picture of yours or any improved one.
Please assign this task to me. I would love to contribute in this page.

**Comment by yash982000** [comment]
@ANSHIKA1806 That task is assigned to someone else as per the FCFS rule. You may have to wait until we get any result from that assignee or I would say you must start with posting some more ideas in the Open to Ideas thread.
I have some other designs for pages as well. Let me know if you can do some complex pages involving inside features of this project.

**Comment by yash982000** [comment]
@ANSHIKA1806 If you are open to working on other screens, let me know, I have some designs ready. Login/Sign-Up has been assigned to another person based on first come first serve.
