### ISSUE TITLE
Login/Signup Page Mobile view not working

### ISSUE THREAD

**Issue by GovindCodes** [ChetnaNSharma/Alumni-Connect#94]
Mobile view of login/signup page is completely distorted

I will make the content dynamic with least use of external libraries(now it is intensive, that make high loading time)

1. Go to 'Login'
2. Click on 'login.html'
3. change to mobile view from inspect

![image](https://user-images.githubusercontent.com/42794725/117576035-e5989d80-b101-11eb-8306-8de0f90bfdcd.png)

If assigned me the task i will fix it in a Day.
ThankYou:)

**Comment by yash982000** [comment]
> Mobile view of login/signup page is completely distorted
> 
> I will make the content dynamic with least use of external libraries(now it is intensive, that make high loading time)
> 
> 1. Go to 'Login'
> 2. Click on 'login.html'
> 3. change to mobile view from inspect
> 4. See error
> 
> ![image](https://user-images.githubusercontent.com/42794725/117576035-e5989d80-b101-11eb-8306-8de0f90bfdcd.png)
> 
> If assigned me the task i will fix it in a Day.
> ThankYou:)

Assigned @GovindCodes
