### ISSUE TITLE
Our reach

### ISSUE THREAD

**Issue by ChitvanRamani22** [ChetnaNSharma/Alumni-Connect#98]
I want to add our reach page as shown in the image below.
![Screenshot_20210513-131628_Gallery.jpg](https://user-images.githubusercontent.com/68965499/118095503-c5acf680-b3ed-11eb-9d30-8296732929d8.jpg)
@yash982000 @ChetnaNSharma 
please assign this to me.

**Comment by yash982000** [comment]
> I want to add our reach page as shown in the image below.
> ![Screenshot_20210513-131628_Gallery.jpg](https://user-images.githubusercontent.com/68965499/118095503-c5acf680-b3ed-11eb-9d30-8296732929d8.jpg)
> @yash982000 @ChetnaNSharma
> please assign this to me.

@ChitvanRamani22 Assigned :)
